HBV/HBV/encuesta/urls.py
from django.conf.urls import url,include
from encuesta.views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, PreguntaList, PreguntaDelete, PreguntaCreate, PreguntaUpdate

app_name="encuesta"
urlpatterns = [
	url(r'^nuevo$',CategoriaCreate.as_view(), name='categoria_crear'),
    url(r'^listar$',CategoriaList.as_view(), name='categoria_listar'),
    url(r'^editar/(?P<pk>\d+)/$',CategoriaUpdate.as_view(), name='categoria_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',CategoriaDelete.as_view(), name='categoria_eliminar'),
    url(r'^listar_pre$',PreguntaList.as_view(), name='pregunta_listar'),
    url(r'^nuevo_pre$',PreguntaCreate.as_view(), name='pregunta_crear'),
    url(r'^editar_pre/(?P<pk>\d+)/$',PreguntaUpdate.as_view(), name='pregunta_editar'),
    url(r'^eliminar_pre/(?P<pk>\d+)/$',PreguntaDelete.as_view(), name='pregunta_eliminar'),
]

HBV/HBV/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from encuesta import views
from encuesta import estadisticasView, encuestaView
from django.contrib.auth.views import login,logout_then_login,password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    path('admin/', admin.site.urls),
    #Urls temporales
    path('entornoAdmin/',include('encuesta.urls',namespace="encuesta")),
    path('entornoUser/', views.entorno_user),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login' ),
    url(r'^logout/', logout_then_login,name='logout'),
    path('estadisticas/', estadisticasView.Estadistica.as_view(), name = "estadisticas"),
    path('encuesta/', encuestaView.Encuesta.as_view(), name = "encuesta"),
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/form.html','email_template_name':'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,{'template_name':'registration/confirmar.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'registration/resetdone.html'},name='password_reset_complete'),
]

HBV/encuesta/urls.py
from django.conf.urls import url,include
from encuesta.views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, PreguntaList, PreguntaDelete, PreguntaCreate, PreguntaUpdate, PreguntaDetail, municipiosPorDepartament, responderEncuesta
from django.contrib.auth.decorators import login_required
from django.urls import path

app_name="encuesta"
urlpatterns = [
    url(r'^nuevo$',login_required(CategoriaCreate.as_view()), name='categoria_crear'),
    url(r'^listar$',login_required(CategoriaList.as_view()), name='categoria_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(CategoriaUpdate.as_view()) ,name='categoria_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(CategoriaDelete.as_view()), name='categoria_eliminar'),
    url(r'^listar_pre$',login_required(PreguntaList.as_view()), name='pregunta_listar'),
    url(r'^nuevo_pre$',login_required(PreguntaCreate.as_view()), name='pregunta_crear'),
    url(r'^editar_pre/(?P<pk>\d+)/$',login_required(PreguntaUpdate.as_view()), name='pregunta_editar'),
    url(r'^eliminar_pre/(?P<pk>\d+)/$',login_required(PreguntaDelete.as_view()), name='pregunta_eliminar'),
    url(r'^detalle_pre/(?P<pk>\d+)/$',login_required(PreguntaDetail.as_view()), name='pregunta_detalle'),
    path('responder-encuesta/', responderEncuesta, name='responder_encuesta'),
    path('municipios/<id_deparmento>/', municipiosPorDepartament, name='municipios'),
]

HBV/encuesta/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
	id_categoria = models.AutoField(db_column = 'id_categoria', primary_key = True)
	descripcion_cat = models.CharField(db_column = 'descripcion_cat', max_length = 100)

	class Meta:
		db_table = 'categoria'


	def __str__(self):
		return '{}'.format(self.descripcion_cat)


class Departamento(models.Model):
	id_depa = models.AutoField(db_column = 'id_depa',primary_key = True)
	nombre_depa = models.CharField(db_column = 'nombre_depa',max_length = 150)

	class Meta:
		db_table = 'departamento'

	def __str__(self):
		return '{}'.format(self.nombre_depa)


class Encuesta(models.Model):
	id_encuesta = models.AutoField(db_column = 'id_encuesta', primary_key = True)
	fk_id_departamento = models.ForeignKey('Departamento', db_column = 'fk_id_departamento', on_delete = models.CASCADE)
	fk_id_municipio = models.ForeignKey('Municipio', db_column = 'fk_id_municipio', on_delete = models.CASCADE)
	fecha = models.DateField(db_column = 'fecha', auto_now_add=True)#default = formatedDay
	hora = models.TimeField(db_column = 'hora', auto_now_add=True)#default = formatedHour

	class Meta:
		db_table = 'encuesta'


class Municipio(models.Model):
	id_municipio = models.AutoField(db_column = 'id_municipio',primary_key = True)
	fk_id_departamento = models.ForeignKey('Departamento', db_column = 'fk_id_departamento', on_delete = models.CASCADE, blank = True, null = True)
	nombre_muni = models.CharField(max_length = 150)

	class Meta:
		db_table = 'municipio'

	def __str__(self):
		return '{}'.format(self.nombre_muni)


class Pregunta(models.Model):
	id_pregunta = models.AutoField(db_column = 'id_pregunta', primary_key = True)
	fk_id_categoria = models.ForeignKey('Categoria', db_column = 'fk_id_categoria', on_delete = models.CASCADE)
	nombre_pre = models.CharField(db_column = 'nombre_pre', max_length = 200)

	class Meta:
		db_table = 'pregunta'


	def __str__(self):
		return '{}'.format(str(self.id_pregunta))


class Respuesta(models.Model):
	id_respuesta = models.AutoField(db_column = 'id_respuesta', primary_key = True)
	fk_id_pregunta = models.ForeignKey('Pregunta', db_column = 'fk_id_pregunta', on_delete = models.CASCADE)
	fk_id_encuesta = models.ForeignKey('Encuesta', db_column = 'fk_id_encuesta', on_delete = models.CASCADE, blank = True, null = True)
	valor = models.IntegerField(db_column = 'valor')

	class Meta:
		db_table = 'respuesta'

HBV/encuesta/forms.py
from django import forms
from encuesta.models import Categoria, Pregunta


#FORMULARIO PARA CREAR CATEGORIA
class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria

		fields = [
			'descripcion_cat',
		]

		labels = {
			'descripcion_cat': 'Descripcion de categoria',
			}

		widgets = {
			'descripcion_cat': forms.TextInput(attrs={'class':'form-control'}),
		}

class PreguntaForm(forms.ModelForm):
	class Meta:
		model = Pregunta

		fields = [
			'nombre_pre',
			'fk_id_categoria',
		]

		labels = {
			'nombre_pre': 'Descripcion de pregunta',
			'fk_id_categoria': 'ID de categoría a la que pertenece',
			}

		widgets = {
			'nombre_pre': forms.TextInput(attrs={'class':'form-control'}),
			'fk_id_categoria': forms.Select(attrs={'class':'form-control'}),
		}

HBV/HBV/encuesta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# *******************CLASES********************************
from django.urls import reverse_lazy
#libreria para vista de tipo lista de django
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
#*********************************************************
from encuesta.forms import CategoriaForm, PreguntaForm
from encuesta.models import Categoria, Pregunta
# Create your views here.

#Vistas temporales

def entorno_admin(request):
	return render(request, 'plantillasBase/baseAdmin.html')

def entorno_user(request):
	return render(request, 'plantillasBase/baseUser.html')
	
#******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR CATEGORIA
class CategoriaList(ListView):
	queryset=Categoria.objects.order_by("id_categoria")
	template_name = 'categoria/categoria_list.html'

class CategoriaCreate(CreateView):
	modelo = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_form.html'
	success_url = reverse_lazy('encuesta:categoria_listar')


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_update.html'
	success_url = reverse_lazy('encuesta:categoria_listar')

class CategoriaDelete(DeleteView):
	model = Categoria
	template_name = 'categoria/categoria_delete.html'
	success_url = reverse_lazy('encuesta:categoria_listar')		
#*******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR PREGUNTA
class PreguntaList(ListView):
	queryset=Pregunta.objects.order_by("id_pregunta")
	template_name = 'pregunta/pregunta_list.htm'

class PreguntaCreate(CreateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_form.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaUpdate(UpdateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_update.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDelete(DeleteView):
	model = Pregunta
	template_name = 'pregunta/pregunta_delete.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')
#*******************************************************************************************************

HBV/encuesta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.core import serializers
import datetime
# *******************CLASES********************************
from django.urls import reverse_lazy
#libreria para vista de tipo lista de django
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
#*********************************************************
from encuesta.forms import CategoriaForm, PreguntaForm
from encuesta.models import Categoria, Pregunta, Municipio, Departamento, Encuesta, Respuesta
# Create your views here.
#Vistas temporales

def entorno_admin(request):
	return render(request, 'plantillasBase/baseAdmin.html')

def entorno_user(request):
	return render(request, 'plantillasBase/baseUser.html')
	
#******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR CATEGORIA
class CategoriaList(ListView):
	queryset=Categoria.objects.order_by("id_categoria")
	template_name = 'categoria/categoria_list.html'

class CategoriaCreate(CreateView):
	modelo = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_form.html'
	success_url = reverse_lazy('encuesta:categoria_listar')


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_update.html'
	success_url = reverse_lazy('encuesta:categoria_listar')

class CategoriaDelete(DeleteView):
	model = Categoria
	template_name = 'categoria/categoria_delete.html'
	success_url = reverse_lazy('encuesta:categoria_listar')		
#*******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR PREGUNTA
class PreguntaList(ListView):
	queryset=Pregunta.objects.order_by("id_pregunta")
	template_name = 'pregunta/pregunta_list.htm'

class PreguntaCreate(CreateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_form.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaUpdate(UpdateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_update.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDelete(DeleteView):
	model = Pregunta
	template_name = 'pregunta/pregunta_delete.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDetail(DetailView):
	model = Pregunta
	template_name = 'pregunta/pregunta_detail.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')
#*******************************************************************************************************
def responderEncuesta(request):
	departamentos = Departamento.objects.all()
	categorias = Categoria.objects.all()

	#Si se envía la encuesta
	if request.method == 'POST':
		
		#Se crea una nueva encuesta
		encuesta = Encuesta()
		
		#Se le asignan valores a las variales para el modelo Encuesta
		fecha = datetime.date.today()
		hora = datetime.datetime.now().strftime('%H:%M:%S')
		departamento = Departamento.objects.get(pk=request.POST['departamento'])
		municipio = Municipio.objects.get(pk=request.POST['municipio'])

		#Se le asignan las variables al modelo encuesta
		encuesta.fecha = fecha
		encuesta.hora = hora
		encuesta.fk_id_departamento = departamento
		encuesta.fk_id_municipio = municipio
		
		#Se registra la encuesta
		encuesta.save()

		#Se obtienen las preguntas enviadas desde el template
		preguntas = request.POST.getlist('preguntas')

		for p in preguntas:
			
			#Se crea una nueva respuesta
			respuesta = Respuesta()

			#Asignación de valores a las variables para el modelo Respuesta
			pregunta = Pregunta.objects.get(pk=p)
			valor = request.POST['pregunta'+p]

			#Asignación de variables al modelo Respuesta
			respuesta.valor = valor
			respuesta.fk_id_encuesta = encuesta
			respuesta.fk_id_pregunta = pregunta

			#Se registra la respuesta
			respuesta.save()

		return redirect('estadisticas')

	context = {
		'departamentos' : departamentos,
		'categorias' : categorias,
	}

	return render(request, 'encuesta/responder_encuesta.html', context)

def municipiosPorDepartament(request, id_deparmento):
	municipios = Municipio.objects.filter(fk_id_departamento=id_deparmento)
	#raise Exception("I want to know the value of this: " + municipios)
	
	municipios = Municipio.objects.filter(fk_id_departamento=id_deparmento)
	municipios_list = serializers.serialize('json', municipios)

	return HttpResponse(municipios_list, content_type="text/json-comment-filtered")

HBV/encuesta/templates/plantillasBase/baseAdmin.html
<!-- Cargar archivos estáticos -->
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <!-- tags metadata requeridos -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Archivos mignificafos y compilados del CSS de Boostrap -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
  <!-- Mi propio css -->
  <link rel="stylesheet" href="{% static 'css/mycss.css' %}"/>
  <!-- Obtener archivos fuentes de Font awesome-->
  <script src="https://kit.fontawesome.com/52edad9896.js" crossorigin="anonymous"></script>
  <!-- Bloque meta -->
  {% block meta %}
  <title>Archivo base | Admin</title>
  {% endblock %}

</head>
<body>
  <!-- Incluir el nav-bar para el entorno del administrador -->
  {% block navbar %}
  {% include "plantillasBase/navbarAdmin.html" %}
  {% endblock %}

  <!-- Bloque para el contenido principal del template -->
  <div class="container mycontainer">
    {% block content %}
    <h1 class="text-center"><i class="fas fa-user-cog"></i> BIENVENIDO</h1>
    {% endblock %}
  </div>

  <!-- Bloque sobre nosotros -->
  {% block sobreN%}
  {% endblock %}

  <!-- Footer -->
  {% block footer %}
  <footer class="navbar-dark bg-dark text-white">
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <p>Universidad de El Salvador -- HBV</p>
    </div>
  </footer>
  {% endblock %}
  <!-- Librerías de jQuery -->
  <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- Archivos compilados de JavaScript -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- Cerrar navbar-collapse cliqueando fuera del nav-bar en mobil-view -->
  <script type="text/javascript">
    function OnwindowClick(elem , action){
      $(document).on('click',function(e){
        if (!$(elem).is(e.target) // if the target of the click isn't the container...
        && $(elem).has(e.target).length === 0) // ... nor a descendant of the container
          {
            action();
          }
      });
    }
    // OnwindowClick(elem , action) add the prevent elements in `elem` something like this
    OnwindowClick('#navbar-collapse', function(){
      $('.navbar-collapse').collapse('hide');
    });
  </script>

  <!-- Bloque script -->
  {% block script %}{% endblock%}

</body>
</html>

HBV/encuesta/templates/plantillasBase/baseUser.html
<!-- Heredar de baseAdmin.html -->
{% extends "plantillasBase/baseAdmin.html" %}

<!-- Modificar contenido del bloque meta -->
{% block meta %}
  <title>Archivo base | User</title>
{% endblock %}

<!-- Modificar contenido del bloque navbar -->
{% block navbar %}
<!-- Inclusión del navbar para el entorno del usuario-->
{% include "plantillasBase/navbarUser.html" %}
{% endblock %}

<!-- Modificar contenido del bloque content-->
{% block content %}
<h1 class="text-center"><i class="fas fa-user"></i> USUARIO</h1>
{% endblock %}

HBV/encuesta/templates/plantillasBase/navbarAdmin.html
<!-- nav-bar para el entorno del administrador -->
  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
    <div class="container">
     <a class="navbar-brand font-weight-bold" href="{% url 'estadisticas' %}">HBV</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <!-- Ver estadísticas -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'estadisticas' %}"><i class="fa fa-eye" aria-hidden="true"></i> Ver estadísticas <span class="sr-only">(current)</span></a>
          </li>
          <!-- Preguntas -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Preguntas
            </a>
            <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item text-white" href="{% url 'encuesta:pregunta_listar'%}"><i class="fa fa-list-alt" aria-hidden="true"></i> Listado de preguntas</a>
              <a class="dropdown-item text-white" href="{%url 'encuesta:pregunta_crear'%}"><i class="fa fa-plus-circle" aria-hidden="true"></i> Nueva pregunta</a>
            </div>
          </li>
          <!-- Categorías -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'encuesta:categoria_listar'%}"><i class="fa fa-list-alt" aria-hidden="true"></i> Categorias <span class="sr-only">(current)</span></a>
          </li>
          <!-- >
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categorías
            </a>
            <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item text-white" href="{% url 'encuesta:categoria_listar' %}"><i class="fa fa-list-alt" aria-hidden="true"></i> Listado de categorías</a>
              <a class="dropdown-item text-white" href="{% url 'encuesta:categoria_crear' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> Nueva categoría</a>

            </div>
          </li>
          <!-->

          <!-- Salir -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout'%}">Salir <i class="fa fa-sign-out" aria-hidden="true"></i><span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

HBV/encuesta/templates/plantillasBase/navbarUser.html
<!-- nav-bar para el entorno del usuario -->
  <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
    <div class="container">
     <a class="navbar-brand font-weight-bold" href="{% url 'estadisticas' %}">HBV</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <!-- Pariticipar llenado encuesta -->
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'encuesta:responder_encuesta' %}"><i class="fas fa-clipboard-list fa-spin" style="color: #FFFFFF;"></i> Llenar encuesta <span class="sr-only">(current)</span></a>
          </li>
          <!-- Sobre nosotros -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'estadisticas' %}#SobreNosotros"><i class="fas fa-users" style="color: #FFFFFF;"></i> Sobre nosotros <span class="sr-only">(current)</span></a>
          </li>
          
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'encuesta:pregunta_listar' %}"><i class="fas fa-user-cog"></i> Admin <span class="sr-only">(current)</span></a>
          </li>
         {% else %}
         

        {% endif %}

        </ul>
      </div>
    </div>
  </nav>