HBV/HBV/encuesta/urls.py
from django.conf.urls import url,include
from encuesta.views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, PreguntaList, PreguntaDelete, PreguntaCreate, PreguntaUpdate

app_name="encuesta"
urlpatterns = [
	url(r'^nuevo$',CategoriaCreate.as_view(), name='categoria_crear'),
    url(r'^listar$',CategoriaList.as_view(), name='categoria_listar'),
    url(r'^editar/(?P<pk>\d+)/$',CategoriaUpdate.as_view(), name='categoria_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',CategoriaDelete.as_view(), name='categoria_eliminar'),
    url(r'^listar_pre$',PreguntaList.as_view(), name='pregunta_listar'),
    url(r'^nuevo_pre$',PreguntaCreate.as_view(), name='pregunta_crear'),
    url(r'^editar_pre/(?P<pk>\d+)/$',PreguntaUpdate.as_view(), name='pregunta_editar'),
    url(r'^eliminar_pre/(?P<pk>\d+)/$',PreguntaDelete.as_view(), name='pregunta_eliminar'),
]

HBV/HBV/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from encuesta import views
from encuesta import estadisticasView, encuestaView
from django.contrib.auth.views import login,logout_then_login,password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    path('admin/', admin.site.urls),
    #Urls temporales
    path('entornoAdmin/',include('encuesta.urls',namespace="encuesta")),
    path('entornoUser/', views.entorno_user),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login' ),
    url(r'^logout/', logout_then_login,name='logout'),
    path('estadisticas/', estadisticasView.Estadistica.as_view(), name = "estadisticas"),
    path('encuesta/', encuestaView.Encuesta.as_view(), name = "encuesta"),
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/form.html','email_template_name':'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,{'template_name':'registration/confirmar.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'registration/resetdone.html'},name='password_reset_complete'),
]

HBV/encuesta/urls.py
from django.conf.urls import url,include
from encuesta.views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, PreguntaList, PreguntaDelete, PreguntaCreate, PreguntaUpdate, PreguntaDetail, municipiosPorDepartament, responderEncuesta
from django.contrib.auth.decorators import login_required
from django.urls import path

app_name="encuesta"
urlpatterns = [
    url(r'^nuevo$',login_required(CategoriaCreate.as_view()), name='categoria_crear'),
    url(r'^listar$',login_required(CategoriaList.as_view()), name='categoria_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(CategoriaUpdate.as_view()) ,name='categoria_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(CategoriaDelete.as_view()), name='categoria_eliminar'),
    url(r'^listar_pre$',login_required(PreguntaList.as_view()), name='pregunta_listar'),
    url(r'^nuevo_pre$',login_required(PreguntaCreate.as_view()), name='pregunta_crear'),
    url(r'^editar_pre/(?P<pk>\d+)/$',login_required(PreguntaUpdate.as_view()), name='pregunta_editar'),
    url(r'^eliminar_pre/(?P<pk>\d+)/$',login_required(PreguntaDelete.as_view()), name='pregunta_eliminar'),
    url(r'^detalle_pre/(?P<pk>\d+)/$',login_required(PreguntaDetail.as_view()), name='pregunta_detalle'),
    path('responder-encuesta/', responderEncuesta, name='responder_encuesta'),
    path('municipios/<id_deparmento>/', municipiosPorDepartament, name='municipios'),
]

HBV/encuesta/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
	id_categoria = models.AutoField(db_column = 'id_categoria', primary_key = True)
	descripcion_cat = models.CharField(db_column = 'descripcion_cat', max_length = 100)

	class Meta:
		db_table = 'categoria'


	def __str__(self):
		return '{}'.format(self.descripcion_cat)


class Departamento(models.Model):
	id_depa = models.AutoField(db_column = 'id_depa',primary_key = True)
	nombre_depa = models.CharField(db_column = 'nombre_depa',max_length = 150)

	class Meta:
		db_table = 'departamento'

	def __str__(self):
		return '{}'.format(self.nombre_depa)


class Encuesta(models.Model):
	id_encuesta = models.AutoField(db_column = 'id_encuesta', primary_key = True)
	fk_id_departamento = models.ForeignKey('Departamento', db_column = 'fk_id_departamento', on_delete = models.CASCADE)
	fk_id_municipio = models.ForeignKey('Municipio', db_column = 'fk_id_municipio', on_delete = models.CASCADE)
	fecha = models.DateField(db_column = 'fecha', auto_now_add=True)#default = formatedDay
	hora = models.TimeField(db_column = 'hora', auto_now_add=True)#default = formatedHour

	class Meta:
		db_table = 'encuesta'


class Municipio(models.Model):
	id_municipio = models.AutoField(db_column = 'id_municipio',primary_key = True)
	fk_id_departamento = models.ForeignKey('Departamento', db_column = 'fk_id_departamento', on_delete = models.CASCADE, blank = True, null = True)
	nombre_muni = models.CharField(max_length = 150)

	class Meta:
		db_table = 'municipio'

	def __str__(self):
		return '{}'.format(self.nombre_muni)


class Pregunta(models.Model):
	id_pregunta = models.AutoField(db_column = 'id_pregunta', primary_key = True)
	fk_id_categoria = models.ForeignKey('Categoria', db_column = 'fk_id_categoria', on_delete = models.CASCADE)
	nombre_pre = models.CharField(db_column = 'nombre_pre', max_length = 200)

	class Meta:
		db_table = 'pregunta'


	def __str__(self):
		return '{}'.format(str(self.id_pregunta))


class Respuesta(models.Model):
	id_respuesta = models.AutoField(db_column = 'id_respuesta', primary_key = True)
	fk_id_pregunta = models.ForeignKey('Pregunta', db_column = 'fk_id_pregunta', on_delete = models.CASCADE)
	fk_id_encuesta = models.ForeignKey('Encuesta', db_column = 'fk_id_encuesta', on_delete = models.CASCADE, blank = True, null = True)
	valor = models.IntegerField(db_column = 'valor')

	class Meta:
		db_table = 'respuesta'

HBV/encuesta/forms.py
from django import forms
from encuesta.models import Categoria, Pregunta


#FORMULARIO PARA CREAR CATEGORIA
class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria

		fields = [
			'descripcion_cat',
		]

		labels = {
			'descripcion_cat': 'Descripcion de categoria',
			}

		widgets = {
			'descripcion_cat': forms.TextInput(attrs={'class':'form-control'}),
		}

class PreguntaForm(forms.ModelForm):
	class Meta:
		model = Pregunta

		fields = [
			'nombre_pre',
			'fk_id_categoria',
		]

		labels = {
			'nombre_pre': 'Descripcion de pregunta',
			'fk_id_categoria': 'ID de categoría a la que pertenece',
			}

		widgets = {
			'nombre_pre': forms.TextInput(attrs={'class':'form-control'}),
			'fk_id_categoria': forms.Select(attrs={'class':'form-control'}),
		}

HBV/HBV/encuesta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# *******************CLASES********************************
from django.urls import reverse_lazy
#libreria para vista de tipo lista de django
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
#*********************************************************
from encuesta.forms import CategoriaForm, PreguntaForm
from encuesta.models import Categoria, Pregunta
# Create your views here.

#Vistas temporales

def entorno_admin(request):
	return render(request, 'plantillasBase/baseAdmin.html')

def entorno_user(request):
	return render(request, 'plantillasBase/baseUser.html')
	
#******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR CATEGORIA
class CategoriaList(ListView):
	queryset=Categoria.objects.order_by("id_categoria")
	template_name = 'categoria/categoria_list.html'

class CategoriaCreate(CreateView):
	modelo = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_form.html'
	success_url = reverse_lazy('encuesta:categoria_listar')


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_update.html'
	success_url = reverse_lazy('encuesta:categoria_listar')

class CategoriaDelete(DeleteView):
	model = Categoria
	template_name = 'categoria/categoria_delete.html'
	success_url = reverse_lazy('encuesta:categoria_listar')		
#*******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR PREGUNTA
class PreguntaList(ListView):
	queryset=Pregunta.objects.order_by("id_pregunta")
	template_name = 'pregunta/pregunta_list.htm'

class PreguntaCreate(CreateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_form.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaUpdate(UpdateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_update.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDelete(DeleteView):
	model = Pregunta
	template_name = 'pregunta/pregunta_delete.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')
#*******************************************************************************************************

HBV/encuesta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.core import serializers
import datetime
# *******************CLASES********************************
from django.urls import reverse_lazy
#libreria para vista de tipo lista de django
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
#*********************************************************
from encuesta.forms import CategoriaForm, PreguntaForm
from encuesta.models import Categoria, Pregunta, Municipio, Departamento, Encuesta, Respuesta
# Create your views here.
#Vistas temporales

def entorno_admin(request):
	return render(request, 'plantillasBase/baseAdmin.html')

def entorno_user(request):
	return render(request, 'plantillasBase/baseUser.html')
	
#******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR CATEGORIA
class CategoriaList(ListView):
	queryset=Categoria.objects.order_by("id_categoria")
	template_name = 'categoria/categoria_list.html'

class CategoriaCreate(CreateView):
	modelo = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_form.html'
	success_url = reverse_lazy('encuesta:categoria_listar')


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_update.html'
	success_url = reverse_lazy('encuesta:categoria_listar')

class CategoriaDelete(DeleteView):
	model = Categoria
	template_name = 'categoria/categoria_delete.html'
	success_url = reverse_lazy('encuesta:categoria_listar')		
#*******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR PREGUNTA
class PreguntaList(ListView):
	queryset=Pregunta.objects.order_by("id_pregunta")
	template_name = 'pregunta/pregunta_list.htm'

class PreguntaCreate(CreateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_form.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaUpdate(UpdateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_update.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDelete(DeleteView):
	model = Pregunta
	template_name = 'pregunta/pregunta_delete.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDetail(DetailView):
	model = Pregunta
	template_name = 'pregunta/pregunta_detail.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')
#*******************************************************************************************************
def responderEncuesta(request):
	departamentos = Departamento.objects.all()
	categorias = Categoria.objects.all()

	#Si se envía la encuesta
	if request.method == 'POST':
		
		#Se crea una nueva encuesta
		encuesta = Encuesta()
		
		#Se le asignan valores a las variales para el modelo Encuesta
		fecha = datetime.date.today()
		hora = datetime.datetime.now().strftime('%H:%M:%S')
		departamento = Departamento.objects.get(pk=request.POST['departamento'])
		municipio = Municipio.objects.get(pk=request.POST['municipio'])

		#Se le asignan las variables al modelo encuesta
		encuesta.fecha = fecha
		encuesta.hora = hora
		encuesta.fk_id_departamento = departamento
		encuesta.fk_id_municipio = municipio
		
		#Se registra la encuesta
		encuesta.save()

		#Se obtienen las preguntas enviadas desde el template
		preguntas = request.POST.getlist('preguntas')

		for p in preguntas:
			
			#Se crea una nueva respuesta
			respuesta = Respuesta()

			#Asignación de valores a las variables para el modelo Respuesta
			pregunta = Pregunta.objects.get(pk=p)
			valor = request.POST['pregunta'+p]

			#Asignación de variables al modelo Respuesta
			respuesta.valor = valor
			respuesta.fk_id_encuesta = encuesta
			respuesta.fk_id_pregunta = pregunta

			#Se registra la respuesta
			respuesta.save()

		return redirect('estadisticas')

	context = {
		'departamentos' : departamentos,
		'categorias' : categorias,
	}

	return render(request, 'encuesta/responder_encuesta.html', context)

def municipiosPorDepartament(request, id_deparmento):
	municipios = Municipio.objects.filter(fk_id_departamento=id_deparmento)
	#raise Exception("I want to know the value of this: " + municipios)
	
	municipios = Municipio.objects.filter(fk_id_departamento=id_deparmento)
	municipios_list = serializers.serialize('json', municipios)

	return HttpResponse(municipios_list, content_type="text/json-comment-filtered")

HBV/encuesta/templates/encuesta/encuesta.html
<!-- Heredar de baseUser.html -->
{% extends "plantillasBase/baseUser.html" %}

<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Modificar contenido del bloque meta -->
{% block meta %}
	<title>Encuesta</title>
{% endblock %}

{% block content %}
<div class="card border-dark mb-3" style="max-width: 100rem;">
 	<div class="card-header text-center">
 		<h2>Encuesta</h2>
 	</div>
 		<div class="card-body text-dark">
 			<form id="regForm" action="." method="post">
 				{% csrf_token %}
  			<br>
    		<h4 class="card-title text-center">Seleccione su departamento y municipio</h4>
    		<br>
    		{% if form.errors %}
					<p class="text-center text-danger" >Por favor verifique los campos</p>
				{% endif %}
    		<div class="row">
    			<div class="col-lg-2">
    			</div>
    			<div class="col-lg-2">
    				{{ form.fk_id_departamento.erros }}
    				{{ form.fk_id_departamento.label_tag }}
    			</div>
    			<div class="col-lg-6">
    				{{ form.fk_id_departamento}}
    			</div>
    			<div class="col-lg-2">
    			</div>
    		</div>
    		<br>
    		<div class="row">
    			<div class="col-lg-2">
    			</div>
    			<div class="col-lg-2">
    				{{ form.fk_id_municipio.erros }}
    				{{ form.fk_id_municipio.label_tag }}
    			</div>
    			<div class="col-lg-6">
    				{{ form.fk_id_municipio}}
    			</div>
    			<div class="col-lg-2">
    			</div>
    		</div>
    		<br>
    		<br>
    		<br>
    		<!-- ENCUESTA -->
    		<div class="content-fluid"><!-- PARA OCULTARLO -->
    			<h5 class="card-title text-center">Proceda con la encuesta</h5>
    			<div class="card-body text-dark">
    				{% if preguntas %}
    					{% for categoria in categorias %}
    						<div class="row">
    							<div class="col-lg-1">
    							</div>
    							<div class="col-lg-11">
    								<br>
    								<h4 class = "text-justify" >
    									{{ categoria.descripcion_cat }}
    								</h4>
  	  						</div>
	    					</div>
    						{% for pregunta in preguntas %}
    							{% if pregunta.fk_id_categoria.id_categoria == categoria.id_categoria %}
    								<div class="row">
    									<div class="col-lg-1">
    									</div>
    									<div class="col-lg-10">
    										<p class = "text-justify" >
    											{{ pregunta.nombre_pre }}
    										</p>
  	  								</div>
  	  								<div class="col-lg-1">
    									</div>
	    							</div>


	    							<div class="row">
    									<div class="col-lg-1">
    									</div>
  	  								<div class="col-lg-11">
	    									<div class="col-lg-2">
	    										<!--<ul id="id_valor">
	    											<li>
	    												<label for="id_valor_0">
	    													<input id="id_valor_0" type="radio" name="{{ pregunta.id_pregunta }}" value = "1" required="">
	    													Si
	    												</label>
	    											</li>
	    											<li>
	    												<label for="id_valor_1">
	    													<input id="id_valor_1" type="radio" name="{{ pregunta.id_pregunta }}" value = "0" required="">
	    													No
	    												</label>
	    											</li>
	    										</ul>-->
	    										<!--{{ form2.valor.errors }}-->
    											<!--<input id="id_valor_0" type="radio" name="{{ pregunta.id_pregunta }}" value = "1">
    											<label for="1">Si</label>-->
    											<!--{{ form2.valor.errors }}-->
    											<!--<input id="id_valor_1" type="radio" name="{{ pregunta.id_pregunta }}" value = "0">
    											<label for="0">No</label><br>-->
    											<!--<input type="radio" id="siInput" name="gender" value="1">
  												<label for="1">Si</label>
  												<input type="radio" id="noInput" name="gender" value="0">
  												<label for="0">No</label>-->
  												<!--{{ form2.valor }}-->
                          <input type="radio" name="choice{{ forloop.counter }}" id="choice{{ forloop.counter }}" value="{{ pregunta.id_pregunta }}" required />
    										</div>
    										<br>
    									</div>
  	  							</div>
    							{% else %}
    							{% endif %}
    						{% endfor %}
    					{% endfor %}
    					<!--{{ form2.valor }}-->
    					<!--{% for pregunta in preguntas %}
    						<div class="row">
    							<div class="col-lg-1">
    							</div>
    							<div class="col-lg-11">
    								<p class = "text-justify" >
    									{{ pregunta.nombre_pre }}
    								</p>
  	  						</div>
	    					</div>-->

    						<!--<div class="row">
    							<div class="col-lg-1">
    							</div>
  	  						<div class="col-lg-11">
	    							<div class="col-lg-2">
    									<input type="radio" name="{{pregunta.id_pregunta}}" value = "1">
    									<label for="1">Si</label>
    									<input type="radio" name="{{pregunta.id_pregunta}}" value = "0">
    									<label for="0">No</label>
    									<input type="radio" id="siInput" name="gender" value="1">
  										<label for="1">Si</label>
  										<input type="radio" id="noInput" name="gender" value="0">
  										<label for="0">No</label>-->
  										<!--{{ form2.valor }}
    								</div>
    							</div>
  	  					</div>
	    					<br>
	    				{% endfor %}-->
    				{% else %}
    				<div class="row">
    					<div class="col-lg-12 text-center">
    						<br>
    						<i class="fas fa-info-circle text-info fa-3x"></i>
    						<br>
    						<h2 class="text-info"> No hay preguntas disponibles</h2>
    						<br>
    						<br>
    					</div>
    				</div>
    				{% endif %}
    			</div>
    		</div>
				<div class="form-group" style="text-align: center; padding: 2%;">
					<button type="submit" class="btn btn-dark">Enviar</button>
    			<!--<button type="button" class="btn btn-secondary">Cancelar</button>-->
    			<a href="{% url 'estadisticas' %}" class="btn btn-secondary">Cancelar</a>
				</div>
			</form>
  	</div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
	preguntas = {{preguntas|safe}};
	a = 0;
	$(document).ready(function () {
  			$("#id_valor_0").attr('name', 'puto');
	});
</script>
{% endblock %}

HBV/encuesta/templates/encuesta/responder_encuesta.html
<!-- Heredar de baseUser.html -->
{% extends "plantillasBase/baseUser.html" %}

<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Modificar contenido del bloque meta -->
{% block meta %}
	<title>Encuesta</title>
{% endblock %}

{% block content %}
<div class="card border-dark mb-3" style="max-width: 100rem;">
 	<div class="card-header text-center">
 		<h2>Encuesta</h2>
 	</div>
    <form method="post" action="{% url 'encuesta:responder_encuesta' %}">
        {% csrf_token %}
 		<div class="card-body text-dark">
    		<h4 class="card-title text-center">Seleccione su departamento y municipio</h4>
    		<div class="row mt-5">
                <div class="col-md-4 ml-5">
                    <div class="form-group">
                        <label for="departamento">Departamentos</label>
                        <select id="departamento" class="form-control" style="width: 100%;" name="departamento">
                            {% if departamentos %}
                                {% for departamento in departamentos %}
                                    <option value="{{ departamento.id_depa }}"> {{ departamento.nombre_depa }} </option>
                                {% endfor %}
                            {% else %}
                                <option id="emptyOption" value="empty"> No hay departamentos </option>
                            {% endif %}
                        </select>
                    </div>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-4 ml-5">
                    <div class="form-group">
                        <label for="municipio">Municipios</label>
                        <select id="municipios" class="form-control" style="width: 100%;" name="municipio">
                            <option id="emptyOption" value="empty"> Seleccione el municipio </option>
                        </select>
                    </div>
                </div>
            </div>
    		<!-- ENCUESTA -->
            <hr>
    		<div class="content-fluid mt-5"><!-- PARA OCULTARLO -->
    			<h4 class="card-title text-center">Proceda con la encuesta</h4>

                <!--mensaje de validación-->
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-10 alert alert-danger text-center collapse ml-1">
                      <h6>Ha dejado preguntas sin responder</h6>
                    </div>
                </div>

    			<div class="card-body text-dark">
                    <div class="row">
                    <div class="col-md-11 ml-5">
                        {% if categorias %}
                        {% for categoria in categorias %}

                        <br>
                        <div class="card">
                          <div class="card-header">
                            <h5><div class="text-center"><b>Categoría:</b> {{ categoria.descripcion_cat }}</div></h5>
                          </div>
                          <div class="card-body ml-2">
                            {% if categoria.pregunta_set.all %}
                            {% for pregunta in categoria.pregunta_set.all %}
                                <input type="hidden" value="{{ pregunta.id_pregunta }}" name="preguntas">
                                <div class="font-weight-bold">{{ forloop.counter }}. {{ pregunta.nombre_pre }}</div>
                                <div class="form-check ml-4 mt-2">
                                  <label class="form-check-label">
                                    <input type="radio" class="form-check-input selecccion" name="pregunta{{pregunta.id_pregunta}}" value="1">Sí
                                  </label>
                                </div>
                                <div class="form-check ml-4">
                                  <label class="form-check-label">
                                    <input type="radio" class="form-check-input selecccion" name="pregunta{{pregunta.id_pregunta}}" value="0">No
                                  </label>
                                </div>
                                {% if not forloop.last %}
                                    <hr>
                                {% endif %}
                            {% endfor %}
                            {% else %}
                                <h4>Esta categría no tiene preguntas</h4>
                            {% endif %}
                          </div>
                        </div>
                        <br>
                        {% endfor %}
                        {% else%}
                            <h4>No hay categorías</h4>
                        {% endif%}
                    </div>
                    </div>
    			</div>
    		</div>
  	</div>
    <div class="card-footer text-right">
        <a href="{% url 'estadisticas' %}" class="btn btn-secondary">Cancelar</a>
        <button type="submit" class="btn btn-primary" id="btnEnviar">Enviar</button>
    </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script type="text/javascript">
	
    //Función para cargar los municipios cuando se seleccione otro departamento
    $('#departamento').on('change', function(){
        html='';
        var id_departamento = $(this).val();

        $.get('/entornoAdmin/municipios/' + id_departamento, function(data){

            for (var i = 0; i < data.length; i++) {
                html += '<option value="' + data[i].pk + '">' + data[i].fields.nombre_muni + '</option>'
            }

            $('#municipios').html(html);
        });
    });

    //Función para cargar los municipio cuando el documentos resté listo
    $(document).ready(function(){
        html='';
        var id_departamento = $('#departamento').val();

        $.get('/entornoAdmin/municipios/' + id_departamento, function(data){

            for (var i = 0; i < data.length; i++) {
                html += '<option value="' + data[i].pk + '">' + data[i].fields.nombre_muni + '</option>'
            }

            $('#municipios').html(html);
        });
    });

    //Validar la seleccion de los radio button
    $('#btnEnviar').on('click', function(){
        var seleccion = $('input[type=radio]:checked').length
        var preguntas = $('input[name=preguntas]').length

        $(this).html(
          '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Enviando...'
        );
        
        if(seleccion != preguntas){
            //Mostrar el mensaje de error
            $(".alert").fadeIn();
            $('html, body').animate({scrollTop:0}, 'slow');

            //Ocultar los mensajes con clase alert después de 3 segunodos
            setTimeout(function() {
                $(".alert").fadeOut();
            },3000);

            $(this).html('Enviar');
            $(this).prop('disabled', false);
            
            return false;
        }
    });
    

</script>
{% endblock %}