HBV/HBV/encuesta/urls.py
from django.conf.urls import url,include
from encuesta.views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, PreguntaList, PreguntaDelete, PreguntaCreate, PreguntaUpdate

app_name="encuesta"
urlpatterns = [
	url(r'^nuevo$',CategoriaCreate.as_view(), name='categoria_crear'),
    url(r'^listar$',CategoriaList.as_view(), name='categoria_listar'),
    url(r'^editar/(?P<pk>\d+)/$',CategoriaUpdate.as_view(), name='categoria_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',CategoriaDelete.as_view(), name='categoria_eliminar'),
    url(r'^listar_pre$',PreguntaList.as_view(), name='pregunta_listar'),
    url(r'^nuevo_pre$',PreguntaCreate.as_view(), name='pregunta_crear'),
    url(r'^editar_pre/(?P<pk>\d+)/$',PreguntaUpdate.as_view(), name='pregunta_editar'),
    url(r'^eliminar_pre/(?P<pk>\d+)/$',PreguntaDelete.as_view(), name='pregunta_eliminar'),
]

HBV/HBV/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from encuesta import views
from encuesta import estadisticasView, encuestaView
from django.contrib.auth.views import login,logout_then_login,password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    path('admin/', admin.site.urls),
    #Urls temporales
    path('entornoAdmin/',include('encuesta.urls',namespace="encuesta")),
    path('entornoUser/', views.entorno_user),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name='login' ),
    url(r'^logout/', logout_then_login,name='logout'),
    path('estadisticas/', estadisticasView.Estadistica.as_view(), name = "estadisticas"),
    path('encuesta/', encuestaView.Encuesta.as_view(), name = "encuesta"),
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/form.html','email_template_name':'registration/password_reset_email.html'}, name = 'password_reset'),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,{'template_name':'registration/confirmar.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'registration/resetdone.html'},name='password_reset_complete'),
]

HBV/encuesta/urls.py
from django.conf.urls import url,include
from encuesta.views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, PreguntaList, PreguntaDelete, PreguntaCreate, PreguntaUpdate, PreguntaDetail, municipiosPorDepartament, responderEncuesta
from django.contrib.auth.decorators import login_required
from django.urls import path

app_name="encuesta"
urlpatterns = [
    url(r'^nuevo$',login_required(CategoriaCreate.as_view()), name='categoria_crear'),
    url(r'^listar$',login_required(CategoriaList.as_view()), name='categoria_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(CategoriaUpdate.as_view()) ,name='categoria_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(CategoriaDelete.as_view()), name='categoria_eliminar'),
    url(r'^listar_pre$',login_required(PreguntaList.as_view()), name='pregunta_listar'),
    url(r'^nuevo_pre$',login_required(PreguntaCreate.as_view()), name='pregunta_crear'),
    url(r'^editar_pre/(?P<pk>\d+)/$',login_required(PreguntaUpdate.as_view()), name='pregunta_editar'),
    url(r'^eliminar_pre/(?P<pk>\d+)/$',login_required(PreguntaDelete.as_view()), name='pregunta_eliminar'),
    url(r'^detalle_pre/(?P<pk>\d+)/$',login_required(PreguntaDetail.as_view()), name='pregunta_detalle'),
    path('responder-encuesta/', responderEncuesta, name='responder_encuesta'),
    path('municipios/<id_deparmento>/', municipiosPorDepartament, name='municipios'),
]

HBV/encuesta/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
	id_categoria = models.AutoField(db_column = 'id_categoria', primary_key = True)
	descripcion_cat = models.CharField(db_column = 'descripcion_cat', max_length = 100)

	class Meta:
		db_table = 'categoria'


	def __str__(self):
		return '{}'.format(self.descripcion_cat)


class Departamento(models.Model):
	id_depa = models.AutoField(db_column = 'id_depa',primary_key = True)
	nombre_depa = models.CharField(db_column = 'nombre_depa',max_length = 150)

	class Meta:
		db_table = 'departamento'

	def __str__(self):
		return '{}'.format(self.nombre_depa)


class Encuesta(models.Model):
	id_encuesta = models.AutoField(db_column = 'id_encuesta', primary_key = True)
	fk_id_departamento = models.ForeignKey('Departamento', db_column = 'fk_id_departamento', on_delete = models.CASCADE)
	fk_id_municipio = models.ForeignKey('Municipio', db_column = 'fk_id_municipio', on_delete = models.CASCADE)
	fecha = models.DateField(db_column = 'fecha', auto_now_add=True)#default = formatedDay
	hora = models.TimeField(db_column = 'hora', auto_now_add=True)#default = formatedHour

	class Meta:
		db_table = 'encuesta'


class Municipio(models.Model):
	id_municipio = models.AutoField(db_column = 'id_municipio',primary_key = True)
	fk_id_departamento = models.ForeignKey('Departamento', db_column = 'fk_id_departamento', on_delete = models.CASCADE, blank = True, null = True)
	nombre_muni = models.CharField(max_length = 150)

	class Meta:
		db_table = 'municipio'

	def __str__(self):
		return '{}'.format(self.nombre_muni)


class Pregunta(models.Model):
	id_pregunta = models.AutoField(db_column = 'id_pregunta', primary_key = True)
	fk_id_categoria = models.ForeignKey('Categoria', db_column = 'fk_id_categoria', on_delete = models.CASCADE)
	nombre_pre = models.CharField(db_column = 'nombre_pre', max_length = 200)

	class Meta:
		db_table = 'pregunta'


	def __str__(self):
		return '{}'.format(str(self.id_pregunta))


class Respuesta(models.Model):
	id_respuesta = models.AutoField(db_column = 'id_respuesta', primary_key = True)
	fk_id_pregunta = models.ForeignKey('Pregunta', db_column = 'fk_id_pregunta', on_delete = models.CASCADE)
	fk_id_encuesta = models.ForeignKey('Encuesta', db_column = 'fk_id_encuesta', on_delete = models.CASCADE, blank = True, null = True)
	valor = models.IntegerField(db_column = 'valor')

	class Meta:
		db_table = 'respuesta'

HBV/encuesta/forms.py
from django import forms
from encuesta.models import Categoria, Pregunta


#FORMULARIO PARA CREAR CATEGORIA
class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria

		fields = [
			'descripcion_cat',
		]

		labels = {
			'descripcion_cat': 'Descripcion de categoria',
			}

		widgets = {
			'descripcion_cat': forms.TextInput(attrs={'class':'form-control'}),
		}

class PreguntaForm(forms.ModelForm):
	class Meta:
		model = Pregunta

		fields = [
			'nombre_pre',
			'fk_id_categoria',
		]

		labels = {
			'nombre_pre': 'Descripcion de pregunta',
			'fk_id_categoria': 'ID de categoría a la que pertenece',
			}

		widgets = {
			'nombre_pre': forms.TextInput(attrs={'class':'form-control'}),
			'fk_id_categoria': forms.Select(attrs={'class':'form-control'}),
		}

HBV/HBV/encuesta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# *******************CLASES********************************
from django.urls import reverse_lazy
#libreria para vista de tipo lista de django
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
#*********************************************************
from encuesta.forms import CategoriaForm, PreguntaForm
from encuesta.models import Categoria, Pregunta
# Create your views here.

#Vistas temporales

def entorno_admin(request):
	return render(request, 'plantillasBase/baseAdmin.html')

def entorno_user(request):
	return render(request, 'plantillasBase/baseUser.html')
	
#******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR CATEGORIA
class CategoriaList(ListView):
	queryset=Categoria.objects.order_by("id_categoria")
	template_name = 'categoria/categoria_list.html'

class CategoriaCreate(CreateView):
	modelo = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_form.html'
	success_url = reverse_lazy('encuesta:categoria_listar')


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_update.html'
	success_url = reverse_lazy('encuesta:categoria_listar')

class CategoriaDelete(DeleteView):
	model = Categoria
	template_name = 'categoria/categoria_delete.html'
	success_url = reverse_lazy('encuesta:categoria_listar')		
#*******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR PREGUNTA
class PreguntaList(ListView):
	queryset=Pregunta.objects.order_by("id_pregunta")
	template_name = 'pregunta/pregunta_list.htm'

class PreguntaCreate(CreateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_form.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaUpdate(UpdateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_update.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDelete(DeleteView):
	model = Pregunta
	template_name = 'pregunta/pregunta_delete.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')
#*******************************************************************************************************

HBV/encuesta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.core import serializers
import datetime
# *******************CLASES********************************
from django.urls import reverse_lazy
#libreria para vista de tipo lista de django
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
#*********************************************************
from encuesta.forms import CategoriaForm, PreguntaForm
from encuesta.models import Categoria, Pregunta, Municipio, Departamento, Encuesta, Respuesta
# Create your views here.
#Vistas temporales

def entorno_admin(request):
	return render(request, 'plantillasBase/baseAdmin.html')

def entorno_user(request):
	return render(request, 'plantillasBase/baseUser.html')
	
#******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR CATEGORIA
class CategoriaList(ListView):
	queryset=Categoria.objects.order_by("id_categoria")
	template_name = 'categoria/categoria_list.html'

class CategoriaCreate(CreateView):
	modelo = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_form.html'
	success_url = reverse_lazy('encuesta:categoria_listar')


class CategoriaUpdate(UpdateView):
	model = Categoria
	form_class = CategoriaForm
	template_name = 'categoria/categoria_update.html'
	success_url = reverse_lazy('encuesta:categoria_listar')

class CategoriaDelete(DeleteView):
	model = Categoria
	template_name = 'categoria/categoria_delete.html'
	success_url = reverse_lazy('encuesta:categoria_listar')		
#*******************************************************************************************************
#VISTAS BASADAS EN CLASES PARA GESTIONAR PREGUNTA
class PreguntaList(ListView):
	queryset=Pregunta.objects.order_by("id_pregunta")
	template_name = 'pregunta/pregunta_list.htm'

class PreguntaCreate(CreateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_form.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaUpdate(UpdateView):
	model = Pregunta
	form_class = PreguntaForm
	template_name = 'pregunta/pregunta_update.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDelete(DeleteView):
	model = Pregunta
	template_name = 'pregunta/pregunta_delete.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')

class PreguntaDetail(DetailView):
	model = Pregunta
	template_name = 'pregunta/pregunta_detail.htm'
	success_url = reverse_lazy('encuesta:pregunta_listar')
#*******************************************************************************************************
def responderEncuesta(request):
	departamentos = Departamento.objects.all()
	categorias = Categoria.objects.all()

	#Si se envía la encuesta
	if request.method == 'POST':
		
		#Se crea una nueva encuesta
		encuesta = Encuesta()
		
		#Se le asignan valores a las variales para el modelo Encuesta
		fecha = datetime.date.today()
		hora = datetime.datetime.now().strftime('%H:%M:%S')
		departamento = Departamento.objects.get(pk=request.POST['departamento'])
		municipio = Municipio.objects.get(pk=request.POST['municipio'])

		#Se le asignan las variables al modelo encuesta
		encuesta.fecha = fecha
		encuesta.hora = hora
		encuesta.fk_id_departamento = departamento
		encuesta.fk_id_municipio = municipio
		
		#Se registra la encuesta
		encuesta.save()

		#Se obtienen las preguntas enviadas desde el template
		preguntas = request.POST.getlist('preguntas')

		for p in preguntas:
			
			#Se crea una nueva respuesta
			respuesta = Respuesta()

			#Asignación de valores a las variables para el modelo Respuesta
			pregunta = Pregunta.objects.get(pk=p)
			valor = request.POST['pregunta'+p]

			#Asignación de variables al modelo Respuesta
			respuesta.valor = valor
			respuesta.fk_id_encuesta = encuesta
			respuesta.fk_id_pregunta = pregunta

			#Se registra la respuesta
			respuesta.save()

		return redirect('estadisticas')

	context = {
		'departamentos' : departamentos,
		'categorias' : categorias,
	}

	return render(request, 'encuesta/responder_encuesta.html', context)

def municipiosPorDepartament(request, id_deparmento):
	municipios = Municipio.objects.filter(fk_id_departamento=id_deparmento)
	#raise Exception("I want to know the value of this: " + municipios)
	
	municipios = Municipio.objects.filter(fk_id_departamento=id_deparmento)
	municipios_list = serializers.serialize('json', municipios)

	return HttpResponse(municipios_list, content_type="text/json-comment-filtered")

HBV/encuesta/templates/categoria/categoria_delete.html
{% extends 'plantillasBase/baseAdmin.html' %}
{% block content %}

{% block meta %}
  <title>Eliminar categoria</title>
{% endblock %}


<form method="post">
	{% csrf_token %}
	<h3>Desea eliminar la categoría: {{ object.descripcion_cat }}?</h3>
	<button class="btn btn-primary" type="submit"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
	<a class="btn btn-dark" href="{% url 'encuesta:categoria_listar' %}"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancelar</a>
	
</form>
{% endblock %}

{% block footer %}

{% endblock %}

HBV/encuesta/templates/categoria/categoria_form.html
{% extends 'plantillasBase/baseAdmin.html' %}

{% block meta %}
  <title>Crear categoria</title>
{% endblock %}

{% block content %}
<div class="alert alert-info" role="alert">
  <h4 class="text-center alert-heading">NUEVA CATEGORIA</h4>
  <p class= "text-center font-weight-bold">Se añadirá una nueva categoría al sistema</p>
</div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button class="btn btn-primary"	type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
    <a class="btn btn-dark" href="{% url 'encuesta:categoria_listar' %}"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancelar</a>
  </form>
{%endblock%}

{% block footer %}

{% endblock %}

HBV/encuesta/templates/categoria/categoria_list.html
{% extends 'plantillasBase/baseAdmin.html' %}
{% block content %}

{% block meta %}
  <title>Listado de categorias</title>
{% endblock %}

<div class="alert alert-info" role="alert">
  <h4 class="text-center alert-heading">LISTADO DE CATEGORIAS</h4>
  <p class="text-center font-weight-bold">Esta es una lista de las categorias existentes en nuestro sistema</p>
</div>
 <!-- ><a class="btn btn-dark btn-block font-weight-bold" href="{% url 'encuesta:categoria_crear' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> Nueva categoría</a>
<hr><!-->

<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th class="text-center font-weight-bold">Id</th>
      <th class="text-center font-weight-bold">Nombre</th>
      <th class="text-center font-weight-bold">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% if object_list %}
    {% for categoria in object_list %}
    <tr>
      <td class="text-center">{{ categoria.id_categoria }}</td>
      <td class="text-center">{{ categoria.descripcion_cat }} </td>
      <td class="text-center">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
          <a class="btn btn-primary btn-sm" href="{% url 'encuesta:categoria_editar' categoria.id_categoria %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Modificar</a>
          <!-- ><a class="btn btn-dark btn-sm" href="{% url 'encuesta:categoria_eliminar' categoria.id_categoria %}"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</a>  
        </div><!-->
      </td>
    </tr>
    {% endfor %}
    {% else %}
    <h2>NO HAY REGISTROS DE CATEGORIA!</h2>
    {% endif %}

  </tbody>
</table>

{% endblock %}

HBV/encuesta/templates/categoria/categoria_update.html
{% extends 'plantillasBase/baseAdmin.html' %}

{% block meta %}
  <title>Actualizar categoria</title>
{% endblock %}

{% block content %}
<div class="alert alert-info" role="alert">
  <h4 class="text-center alert-heading">MODIFICAR CATEGORIA</h4>
  <p class= "text-center font-weight-bold">Se hará una modificación de una categoría existente seleccionada por el administrador</p>
</div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button class="btn btn-primary"	type="submit"><i class="fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
    <a class="btn btn-dark" href="{% url 'encuesta:categoria_listar' %}"><i class="fa fa-times-circle" aria-hidden="true"></i> Cancelar</a>
  </form>
{%endblock%}

{% block footer %}

{% endblock %}